on:
  push:

env:
  IMAGE_NAME: boatrace-crawler
  IMAGE_VERSION: 1.6.0-dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Setup dotenv
        run: cp .env.original .env
      - name: Start MiniO
        run: docker compose up -d s3
      - name: Start RabbitMQ
        run: docker compose up -d mq
      - name: Lint
        run: docker compose run app poe lint
      - name: Test
        run: |
          docker compose run app poe test
          docker compose run app poe test_pastodds

  push:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Repository
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push to GitHub Container Registry
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}
